### PR TITLE
Integrated GitHub Actions to continuously precompile latest binaries

### PR DESCRIPTION
**Pull request by cieldeville**
Dear Mr Edwards,

a friend of mine, Leon Focker, who I had previously helped in compiling your project for PD on Windows has told me you had asked him whether it would be possible for him to provide updated binaries whenever you updated the project.

I have written a short GitHub Actions workflow that provides precompiled binaries of mdeGranular for PD for Linux, Mac OSX and Windows whenever any new commit is pushed onto the repository's master branch. Once the build is complete, all compiled binaries may be downloaded from the repository's Actions tab here on GitHub. You can see how the workflow works for yourself in the repository I have opened this pull request from: [see here](https://github.com/cieldeville/mdeGranular/actions/runs/962869452).

This should hopefully simplify the deployment of your PD extension as you will no longer have to keep any binaries up-to-date manually. I have therefore deleted the respective files from the repository on my fork.

I have verified that the binary output for Windows does actually work with PD. You might need to verify the same for both Mac OSX and Linux since I currently do not own a Mac OSX system or have PD installed on Linux.

Should you have any further questions or should you need further assistance in getting the CI to work just right please feel free to reach out.

Best regards,
René-Maurice Hanne.

### CODE REVIEW

**Comment by mdedwards** [comment]
Dear Mr. Hanne,

How very nice of you! I don’t suppose you fancy including the builds for MaxMSP on Windows etc.?  That’s cheeky of course, but I don’t have a PC and so actually can’t offer that to my students etc. It’s a bit of a pain to be honest. I haven’t looked yet but am guessing you’re using cmake or similar, right?

Perhaps you and I could have an online chat soon so you can talk me through your process. We’ll need to check that everything works of course, somehow.

Best, Michael

**Comment by cieldeville** [comment]
Dear Mr Edwards,

I can certainly try to get those integrated as well, though it might take me until next week to do so. As for an online chat we can probably have one the coming week as well, if that would work for you.

From the bit of messing around I could successfully compile an .mxe64 object under Windows (64-bit) but since I do not have a license for the MaxMSP software package I'm afraid I'm unable to test whether or not it actually works. Do you have any way of verifying whether or not the build was successful? You can download the binaries I compiled here (link will expire after 30 days): [Download from external hosting provider](https://easyupload.io/ioiq2d). Integrating the procedure I built the binaries with should not be a problem per se, but I would need to know whether or not they are actually usable before writing the respective workflows.

Best regards,
René.

**Comment by mdedwards** [comment]
Hi René,

> Dear Mr Edwards,

Please call me Michael.

> I can certainly try to get those integrated as well, though it might take me until next week to do so.

This is very much appreciated.

> 
> From the bit of messing around I could successfully compile an .mxe64 object under Windows (64-bit) but since I do not have a license for the MaxMSP software package I'm afraid I'm unable to test whether or not it actually works.

Actually you only need a licence to save Max files. You can open and run patches without paying. You could try the demo patch for max that’s on GitHub.

> Do you have any way of verifying whether or not the build was successful? 

Merely by loading and running but as I don’t have windows I can’t test that either.

All the best, Michael

**Comment by cieldeville** [comment]
Hi Michael,

I have actually found the time to add the MaxMSP build routines already (see my last two commits). Leon tested out the MaxMSP version on Windows for me and he told me it seemed to work for him (it loaded and the object was accessible). We will test the Linux and Windows PD builds as well but neither of us currently have a Mac - if you could load and run the builds on Mac OS that would be great!

You can find all the binaries that are currently being compiled here: [Action](https://github.com/cieldeville/mdeGranular/actions/runs/965297783)

Assuming every build works as intended, are there any other platforms you need the binaries built for?

Best regards,
René

**Review by mdedwards — APPROVED** [review]

**Comment by mdedwards** [comment]
Hi René,

Sorry for the delay.

> I have actually found the time to add the MaxMSP build routines already (see my last two commits). Leon tested out the MaxMSP version on Windows for me and he told me it seemed to work for him (it loaded and the object was accessible). We will test the Linux and Windows PD builds as well but neither of us currently have a Mac - if you could load and run the builds on Mac OS that would be great!

I just did that and it works perfectly. Many, many thanks!

> You can find all the binaries that are currently being compiled here: Action
> 
> Assuming every build works as intended, are there any other platforms you need the binaries built for?

None I can think of right now. I’ve just handled your pull request and merged the actions into my master branch.

GitHub is now running the workflow so I assume when it’s finished all binaries will be automagically placed into their respective pd/max directories.

I can’t thank you enough for this. I’d really appreciate a chat at some point about how you’ve gone about this, as I’ve not had the time to look into these aspects of GitHub. Maybe you have time for this over the summer?

Best, Michael

**Comment by cieldeville** [comment]
Hi Michael!

No worries!

I'm glad to hear it worked as intended! Should the need for any further build variants arise in the future, drop me a message and I'll try to integrate those as well.

GitHub is indeed running the workflow now. However, the resulting binaries do not get uploaded into the pd and max directories as that would require another commit once the workflow is finished. Any commit to master would trigger the workflow again and the workflow would then trigger itself in a never-ending cycle. The repository's 'Actions' tab lists all previous runs of the workflow. Simply click on the latest one and you can find downloads for all produced binaries (labelled Artifacts) on its Summary page (see [here](https://github.com/mdedwards/mdeGranular/actions/runs/970593257) for an example).

I'm happy to hear this helped you out! Like I said before I'd probably be able to have a chat the coming week (or the week thereafter) - let me know when you'll be free.

Best regards,
René.

**Comment by mdedwards** [comment]
Gotcha, thanks René. maybe we can  speak this coming Friday afternoon? Best, Michael

**Pull request merged**
